# Generated by Django 4.0.3 on 2023-06-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='interviewees',
            field=models.ManyToManyField(blank=True, related_name='interviewees', to='accounts.interviewee'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
