# Generated by Django 4.0.3 on 2023-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_panel_interviewees_alter_panel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='bool',
            field=models.BooleanField(default=False),
        ),
    ]
