# Generated by Django 4.0.3 on 2023-07-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_score_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.question'),
        ),
        migrations.AlterField(
            model_name='score',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.applicationstack'),
        ),
    ]
